batch_size: 4
beta1: 0.9
beta2: 0.999
dataset_name: yzl
height: 256
lambda1: 1.0    # 1.0
lambda2: 0.01
learning_rate: 0.0002
loss_function_name: GAN
max_epoch: 400
model: bedsrnet
num_workers: 4
pretrained: False
width: 256
